### ISSUE TITLE
Version number checks don't work with GitHub era MESA releases

### ISSUE THREAD

**Issue by evbauer** [wmwolf/MesaScript#10]
Since MESA no longer has integer version numbers, these checks don't work any more:
https://github.com/wmwolf/MesaScript/blob/31a50922045ec73076845cd46b2cf26fba669f62/mesa_script/lib/mesa_script.rb#L15
https://github.com/wmwolf/MesaScript/blob/31a50922045ec73076845cd46b2cf26fba669f62/mesa_script/lib/mesa_script.rb#L24

I was able to temporarily hack around this by simply deleting the check and assuming I'm working with a more recent MESA version. MesaScript seems to be working fairly well otherwise (though it doesn't know about the `kap` and `eos` inlists of more recent MESA versions), so I think it's probably worth patching this and updating the gem.

**Comment by wmwolf** [comment]
Ok, that's a fair use case, and I'll have to do something a little more complicated. Since it's impossible to determine order from a git hash alone, I'll just add in a separate check to see if the version is a git hash, and then those particular checks will see if the the version is a git hash OR if it is greater than some number.

While I'm at this, I'm going to try to add the new inlists (and I should probably add in astero, too). Any idea around what version `&kap` and `&eos` came to be?

**Comment by wmwolf** [comment]
I just pushed version 0.2.1 out. It should address the version issues, and it should support `&eos` and `&kap` out of the box. Could you give it a try to see if it works? Update with `gem update mesa_script`.

I did not test thoroughly, the the sample case works (with a few small tweaks), and I was able to at least get an eon and cap control working.

**Comment by evbauer** [comment]
Fantastic! The updated gem works great for everything I've tested so far, which I think covers all of what I was hoping for.

**Comment by wmwolf** [comment]
Hurray! I'll issue a new release, then.
