### ISSUE TITLE
Binary Support?

### ISSUE THREAD

**Issue by branbauep** [wmwolf/MesaScript#2]
binary_job and binary_project inlist options don't appear to be supported currently. How hard would that be to add?

**Comment by wmwolf** [comment]
So long as their aren’t any name collisions between the binary and star namelist commands, it should be extremely easy. If there are name collisions... I don't actually know what would happen. It would be bad, though, and the code can't handle that. By name collision, I mean commands in two different namelists with the same name.

If you look in the mesa_script.rb file (mesa_script/lib/mesa_script.rb in the repo), lines 23-46 might be of interest:

```ruby
# Different namelists can be added or subtracted if MESA should change or
# proprietary inlists are required. Later hashes should be edited in a
# similar way to get the desired behavior for additional namelists.

#################### ADD NEW NAMELISTS HERE ####################
@namelists = %w{ star_job controls pgstar }
################## POINT TO .INC FILES HERE ####################
@nt_files = {
              'star_job' => %w{star_job_controls.inc},
              'controls' => %w{star_controls.inc},
              'pgstar'   => %w{pgstar_controls.inc},
            }
@nt_files['controls'] << "ctrls_io.#{f_end}"
# User can specify a custom name for a namelist defaults file. The default
# is simply the namelist name followed by '.defaults'

################ POINT TO .DEFAULTS FILES HERE #################
@d_files = {}

# User can add new paths to namelist default files through this hash

############ GIVE PATHS TO .INC AND .DEF FILES HERE ###########
@nt_paths = Hash.new(ENV['MESA_DIR'] + '/star/private/')
@d_paths = Hash.new(ENV['MESA_DIR'] + '/star/defaults/')
```

The naming conventions I chose are a bit opaque, but you can add new namelists (like binary_job and binary_project) to the `@namelists` array and then add a new entry in the `@nt_files` and `@nt_paths` objects to point to where the actual namelist objects are declared in fortran (I don’t remember what nt means… sorry about that, but the standard star namelists should give you an idea of what we need).

Finally we'd need to point `@d_paths` and `@d_files` to the proper defaults folders and files, respectively. This would probably mean something like

`@d_paths['binary_job'] = File.join(ENV['MESA_DIR'], 'binary', 'defaults')`

and much the same for `'binary_project'`. The default value for the default file name should be sufficient (simply the namelist name followed up with `'.defaults'`.

If all of that is set up, the binary namelists should work like the others, but I have never actually tested this. `binary` was in a state of upheaval when I wrote MesaScript, and due to its surprising robustness, I haven't had to edit much of MesaScript's innards since its original release. 

At some point I'd prefer to outsource this stuff to a config file so you don't have to muck around with the code, but this is the first time someone has asked about adding additional namelists.

**Comment by branbauep** [comment]
Cool! I think I got it working. I'll need to do a little validation, but it's looking pretty good. I'm still trying to figure out "binary_job", since it's a little weird, but "binary_controls" (which I mistakenly called binary_project earlier) seems to be straightforward. Remind me to submit a pull request if I haven't by end of tomorrow.

**Comment by branbauep** [comment]
Hmmm, one error arose. It turns out "binary_controls" has at least one name collision that I've run into. Happily (?) it doesn't throw any major error. It just always puts the thing called "log_directory" into a "binary_controls" section of any namelist it makes now, rather than the "controls" section that I want it to go into.

**Comment by wmwolf** [comment]
Ok, looks like a more general solution is needed. I have something in mind, but it might have to wait a bit until I've gotten some job applications out the door. In the end I'd like to have a syntax like

```Ruby
namelist "binary_controls" do
  log_directory "binary_LOGS"
end

namelist "controls" do
  log_directory "star_LOGS"
end
```
That would allow for bulk assignments (many methods could be called in the do block) and an optional parameter `namelist` for every method that would force it to go under the proper namelist, if possible. That would be useful for one-off cases where the block syntax isn't really needed.

**Comment by wmwolf** [comment]
This has been partially solved by adding support for `binary_controls` by default, but the `log_directory` command is now _only_ recognized as belonging to the `controls` namelist and _cannot_ be used in the `binary_controls` namelist. Thanks for the pull request, @branbauep!

A more elegant solution that would also allow for `binary_job` to be included may come in the future, but for now, we have most of the functionality that is needed.
